- name: Provision / update hosts
  become: true
  become_user: root
  hosts: '{{ target | default("all") }}'
  roles:
    - aur
    - audio
    - boot
    - cpu
    - devel
    - kernel
    - print_3d
  vars:
    rebuild_bootloader: false
    rebuild_initramfs: false
