---
- name: Provision / update hosts
  become: true
  become_user: root
  hosts: '{{ target | default("all") }}'
  roles:
    - aur
    - base
    - devel
    - print_3d
  vars:
    rebuild_bootloader: false
    rebuild_initramfs: false
    user:
      username: kjkent
