- name: Install audio packages (pacman)
  community.general.pacman:
    name:
      - alsa-utils
      - audacity
      - easyeffects
      - ffmpeg
      - imv
      - mpv
      - pavucontrol
      - playerctl
      - vlc

- name: Install audio packages (AUR)
  kewlfft.aur.aur:
    name:
      - spotify
      - spotx-git
