- name: "Set console keyboard layout"
  ansible.builtin.copy:
    content: {{ kb_layout.console }}
    dest: /etc/vconsole
    force: true

- name: Set system locale
  community.general.locale_gen:
    name: en_GB.UTF-8
    state: present
