- name: Audio configuration
  ansible.builtin.include_tasks: 
    - audio.yaml
    - boot.yaml
    - firmware.yaml
    - kernel.yaml
    - laptop.yaml
    - locale.yaml
    - login.yaml
    - security.yaml
    - zram.yaml
