---
- name: Set zram kernel sysctls
  ansible.posix.sysctl:
    - name: vm.swappiness
      value: "180"
    - name: vm.watermark_boost_factor
      value: "0"
    - name: vm.watermark_scale_factor
      value: "125"
    - name: vm.page-cluster
      value: "0"

- name: Install zram-generator
  ansible.builtin.package:
    name: zram-generator
    state: present

- name: Configure zram-generator
  ansible.builtin.copy:
    path: /etc/systemd/zram-generator.conf
    owner: root
    group: root
    mode: "0600"
    content: |
      [zram0]
      zram-size = min(ram / 2, 4096)
      compression-algorithm = zstd

- name: Disable zswap (conflicts with zram)
  block:
    - name: Disable zswap for future boots
      ansible.builtin.lineinfile:
        path: /etc/dracut.conf
        create: true
        mode: "0600"
        state: present
        line: kernel_cmdline+=" zswap.enabled=0 "

    - name: Disable zswap for running system
      ansible.builtin.shell: |
        echo 0 > /sys/module/zswap/parameters/enabled
      changed_when: true

- name: Start zram-generator
  ansible.builtin.systemd_service:
    name: systemd-zram-setup@zram0.service
    daemon_reload: true
    state: started
