- name: Install AMD microcode package
  when: '"AuthenticAMD" in ansible_processor'
  ansible.builtin.package:
    name: amd-ucode
    state: present

- name: Install Intel microcode package
  when: '"GenuineIntel" in ansible_processor'
  ansible.builtin.package:
    name: amd-ucode
    state: absent

- name: Install fwupd
  ansible.builtin.package:
    name: fwupd
    state: present
